name: Bug report
description: Report bugs with the engine here
labels: ["Type: Bug","Awaits labels"]
body:
  - type: textarea
    id: description
    attributes:
      
      label: "Describe your bug here."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Terminal logs (latest.log)"
      render: bash
    validations:
      required: false

  - type: textarea
    id: modding
    attributes:
      label: "Are you modding your build? If so, enter the mods/scripts installed."
    validations:
      required: true  
      
  - type: input
    id: user-id
    attributes:
      label: "For mobile: Enter here your UserID (you can find it in latest.log)"
      placeholder: "123" 

  - type: input
    id: pslice-version
    attributes:
      label: "In which version of P-Slice this occurs in (if it's the build from the Actions tab, then also include the commit hash of the build)"
      placeholder: "3.2.1"
    validations:
      required: true

  - type: dropdown
    id: psych
    attributes:
      label: "Which \"Psych engine\" version of P-Slice this occurs in"
      options:
        - 0.6.3
        - 1.0.4
        - Both
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "What platform did the issue occur?"
      options:
        - "Windows"
        - "Linux"
        - "Mac"
        - "Android"
        - "iOS"
        - "HTML5"
    validations:
      required: true
      


